name: Build & Publish ASP.NET Core API

on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x', '10.0.x']

    name: Build avec .NET ${{ matrix.dotnet-version }}

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Installation de la version .NET (stratégie)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restauration des dépendances
        run: dotnet restore

      - name: Compilation
        run: dotnet build --configuration Release --no-restore

      - name: Publication
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Création d'une archive
        run: |
          cd publish
          zip -r ../api-${{ matrix.dotnet-version }}.zip .

      - name: Upload des artefacts
        uses: actions/upload-artifact@v4
        with:
          name: api-${{ matrix.dotnet-version }}
          path: api-${{ matrix.dotnet-version }}.zip